### PR TITLE
Fix github link

### PR DESCRIPTION
**Pull request by giodamelio**
You switched some letters.

### CODE REVIEW

**Comment by alexgorbatchev** [comment]
Thank you, much appreciated! Would you be interested in writing about a module? :) I'm actively looking for guest contributors.

**Comment by giodamelio** [comment]
Maybe if I find something interesting.

**Comment by alexgorbatchev** [comment]
Great, keep me posted!

**Comment by giodamelio** [comment]
Will do

On Thursday, March 6, 2014, Alex Gorbatchev notifications@github.com
wrote:

> Great, keep me posted!
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/alexgorbatchev/npm-awesome-site/pull/3#issuecomment-36921340
> .

## 

Gio d'Amelio
giodamelio@gmail.com

**Pull request merged**
