### PR TITLE
Link to both github and browsenpm.org and show License.

### PR DESCRIPTION
**Pull request by Swaagie**
In the DailyJS style @indexzero mentioned earlier.

> There are database specific ORM libraries such as [Mongoose](#) (Github: Learnboost/mongoose, License: MIT)
- Initial bulk changes done by simple automatic script, see https://gist.github.com/Swaagie/4ce46905d323100d0016 (nothing fancy)
- Manually checked each file for false positives or missing links.
- Added small browsenpm function helper to `docpad.coffee` to easily link to the package

Hope I covered all my bases, will do the same with the Nodejitsu blog content. Thanks!

### CODE REVIEW

**Comment by alexgorbatchev** [comment]
I would really like to continue using a function to generate the `[angular-injector][browsenpm] (Github: [alexgorbatchev/angular-injector][github], License: MIT)` boilerplate. Most of the information is already available in the meta tags for the majority of posts (except the older once which were backported from another site generator).

This makes it easier to keep all meta info in the header and reduces amount of time that it takes to write each post.

I would suggest either extending `npm()` function with options or making another one along the lines of `npmFull()`

**Comment by Swaagie** [comment]
Sure sounds good, should be a straightforward change. I'm not sure it works for all linked modules though, a few posts (marginally) have a multiple modules (other than the highlight module) linked in the same fashion . I'll check if I can do those in a smart way as well. 

edit: something I'll look at tomorrow

**Comment by alexgorbatchev** [comment]
We could also have a helper function, something like this: `npmLink(displayName, github, license)` and `npmFull()` could call it with default document meta.

**Comment by Swaagie** [comment]
https://github.com/nodejitsu/npmawesome.com/commit/40438c07da371898881d5c49d0dd614815552ea5 should have this covered right? I'm no coffeescripter but shouldn't we call the`reference` helper with an `object`? I'll add displayName to the document meta data.

**Comment by Swaagie** [comment]
Every post should be using `<%- @reference() %>` as much as possible.

**Comment by alexgorbatchev** [comment]
Merged with a couple of fixes. Thanks!

**Comment by Swaagie** [comment]
Thank you! :+1:

**Pull request closed without merging**
